version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "gh actions dependencies"
    reviewers:
      - "music-encoding/technical-team-co-chairs"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Ruby
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      # Check for updates on the first day of every month
      interval: "monthly"
    labels:
      - "dependencies"
    reviewers:
      - "music-encoding/technical-team-co-chairs"
    groups:
      bundler-dependencies:
        patterns:
          - "*"
