version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "gh actions dependencies"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Ruby
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      bundler-dependencies:
        patterns:
          - "*"
