name: Link Checker

on:
  schedule:
    - cron: "0 13 * * 0" # run every Sunday at 1pm UTC https://crontab.guru/#0_13_*_*_1
  workflow_dispatch: # trigger manually
    inputs:
      branch:
        description: "Branch to check"
        required: true
        default: main

# globals
env:
  CHECK_WEBSITE: https://music-encoding.org
  CHECK_OWNER: music-encoding
  CHECK_BRANCH: main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: bug, documentation
